baseURL = "https://off.gaelaguiar.net"
languageCode = "en-us"
title = "Gael Aguiar"
theme = "hello-friend-ng"
disableKinds = ["sitemap"]

[pagination]
  pagerSize = 10

[params]
  description = "Professional homepage by Gael Aguiar"
  keywords = "homepage, professional, computer, science, development, programming, technology"
  images = [""]

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/gael-aguiar"

  [[params.social]]
    name = "github"
    url = "https://github.com/64gag"

[taxonomies]
  category = "categories"
  tag = "tags"

[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact"

[outputs]
  home = ["HTML", "JSON", "RSS"]
